-- Run once in Snowsight (Workspaces > My Workspace > + SQL file > paste > Run all) as ACCOUNTADMIN.
-- Sets up a cheap, capped environment so the $400 trial credit lasts.

USE ROLE ACCOUNTADMIN;

-- Hard spending cap: suspend everything at 300 credits (~75% of trial), warn earlier.
CREATE RESOURCE MONITOR IF NOT EXISTS LAKE_MONITOR
  WITH CREDIT_QUOTA = 300
  FREQUENCY = NEVER
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 50 PERCENT DO NOTIFY
           ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND_IMMEDIATE;
ALTER ACCOUNT SET RESOURCE_MONITOR = LAKE_MONITOR;

-- Smallest warehouse, sleeps after 60s idle. This is where nearly all cost comes from.
CREATE WAREHOUSE IF NOT EXISTS LAKE_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS LAKE;
CREATE SCHEMA IF NOT EXISTS LAKE.BRONZE;     -- raw tables, loaded by snowflake/load_bronze.py
CREATE SCHEMA IF NOT EXISTS LAKE.DEV;        -- dbt target (dbt creates DEV_SILVER / DEV_GOLD beside it)

-- A non-admin role for day-to-day work (what you'd have at a real job).
CREATE ROLE IF NOT EXISTS LAKE_DEV;
GRANT USAGE ON WAREHOUSE LAKE_WH TO ROLE LAKE_DEV;
GRANT USAGE ON DATABASE LAKE TO ROLE LAKE_DEV;
GRANT CREATE SCHEMA ON DATABASE LAKE TO ROLE LAKE_DEV;
GRANT ALL ON SCHEMA LAKE.BRONZE TO ROLE LAKE_DEV;
GRANT ALL ON SCHEMA LAKE.DEV TO ROLE LAKE_DEV;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE LAKE TO ROLE LAKE_DEV;
GRANT ALL ON FUTURE TABLES IN DATABASE LAKE TO ROLE LAKE_DEV;
GRANT ALL ON FUTURE VIEWS IN DATABASE LAKE TO ROLE LAKE_DEV;
GRANT ROLE LAKE_DEV TO USER "michaelvhaug";
GRANT ROLE LAKE_DEV TO USER LAKE_SVC;        -- pipeline service user (see 02_service_user.sql)

-- Internal stage the loader PUTs Parquet into. Tables are created from the files' schemas.
USE ROLE LAKE_DEV;
USE WAREHOUSE LAKE_WH;
CREATE FILE FORMAT IF NOT EXISTS LAKE.BRONZE.PARQUET_FMT TYPE = PARQUET USE_LOGICAL_TYPE = TRUE;
CREATE STAGE IF NOT EXISTS LAKE.BRONZE.BRONZE_STAGE FILE_FORMAT = LAKE.BRONZE.PARQUET_FMT;
